let currentUser=null,projects=[],profile=null;
async function init(){currentUser=await requireAuth();if(!currentUser)return;document.getElementById("user-email").textContent=currentUser.email||"";await Promise.all([loadProfile(),loadProjects()]);setupRealtime()}
async function loadProfile(){const {data,error}=await supabaseClient.from("profiles").select("credits,name,full_name,avatar_url").eq("id",currentUser.id).maybeSingle();if(error){showToast("تعذر تحميل الرصيد: "+error.message,"error");return}profile=data||{};renderCredits()}
function renderCredits(){const c=Math.max(0,Number(profile?.credits??0));document.getElementById("credits-value").textContent=c+" / 50";document.getElementById("credits-pill").textContent="⚡ "+c+" / 50";document.getElementById("credits-pill").title="رصيد الصور اليومي"}
async function loadProjects(){loading.style.display="block";const {data,error}=await supabaseClient.from("projects").select("id,title,prompt,language,style,status,created_at,updated_at,scenes(id,image_url),render_jobs(id,status,output_url,error_message,created_at)").eq("user_id",currentUser.id).is("deleted_at",null).order("created_at",{ascending:false});loading.style.display="none";if(error)return showToast("فشل تحميل المشاريع: "+error.message,"error");projects=data||[];updateStats();renderProjects()}
function updateStats(){document.getElementById("stat-total").textContent=projects.length;document.getElementById("stat-completed").textContent=projects.filter(p=>(p.render_jobs||[]).some(j=>j.status==="completed")).length;document.getElementById("stat-processing").textContent=projects.filter(p=>(p.render_jobs||[]).some(j=>["queued","processing"].includes(j.status))).length}
function renderProjects(){const g=document.getElementById("projects-grid"),e=document.getElementById("empty-state");if(!projects.length){g.style.display="none";e.style.display="block";return}g.style.display="grid";e.style.display="none";g.innerHTML=projects.map(projectCard).join("")}
function esc(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}
function projectCard(p){const im=(p.scenes||[]).find(s=>s.image_url)?.image_url||"";const jobs=p.render_jobs||[];let badge='<span class="badge badge-draft">مسودة</span>';if(jobs.some(j=>j.status==="completed"))badge='<span class="badge badge-success">جاهز</span>';else if(jobs.some(j=>j.status==="processing"))badge='<span class="badge badge-processing">قيد الرندر</span>';else if(jobs.some(j=>j.status==="queued"))badge='<span class="badge badge-queued">في الانتظار</span>';else if(jobs.some(j=>j.status==="failed"))badge='<span class="badge badge-failed">فشل</span>';const images=(p.scenes||[]).filter(s=>s.image_url).length;const videos=jobs.filter(j=>j.status==="completed").length;return '<article class="project-card"><div class="project-thumb" style="background-image:url(\''+esc(im)+'\')">'+badge+'<button class="card-menu" onclick="renameProject(\''+p.id+'\')" aria-label="إعادة التسمية">⋮</button></div><div class="project-info"><h3>'+esc(p.title)+'</h3><div class="project-meta"><span>'+images+' صور · '+videos+' فيديو</span><span>'+new Date(p.created_at).toLocaleDateString("ar-MA")+'</span></div></div><div class="project-actions"><a href="/project.html?id='+encodeURIComponent(p.id)+'">فتح</a><button onclick="renameProject(\''+p.id+'\')">تسمية</button><button onclick="duplicateProject(\''+p.id+'\')">نسخ</button><button onclick="deleteProject(\''+p.id+'\')">حذف</button></div></article>'}
async function renameProject(id){const p=projects.find(x=>x.id===id);if(!p)return;const next=prompt("اسم المشروع:",p.title);if(!next||next.trim()===p.title)return;const {error}=await supabaseClient.from("projects").update({title:next.trim(),updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",currentUser.id);if(error)return showToast(error.message,"error");showToast("تم تغيير اسم المشروع","success");await loadProjects()}
async function duplicateProject(id){const o=projects.find(p=>p.id===id);if(!o||!confirm("هل تريد إنشاء نسخة من هذا المشروع؟"))return;const {data:n,error}=await supabaseClient.from("projects").insert({user_id:currentUser.id,title:o.title+" (نسخة)",prompt:o.prompt||o.title,language:o.language||"Arabic",style:o.style||"informative",status:"draft"}).select().single();if(error)return showToast(error.message,"error");const {data:ss,error:se}=await supabaseClient.from("scenes").select("scene_index,title,visual_prompt,image_url,sfx_prompt,sfx_url,duration_seconds,status").eq("project_id",id).order("scene_index");if(se)return showToast(se.message,"error");if(ss?.length){const clean=ss.map(s=>({...s,project_id:n.id,status:s.status==="failed"?"draft":s.status}));const {error:ie}=await supabaseClient.from("scenes").insert(clean);if(ie)return showToast(ie.message,"error")}showToast("تم إنشاء النسخة بنجاح","success");await loadProjects()}
async function deleteProject(id){const p=projects.find(x=>x.id===id);if(!p||!confirm('هل أنت متأكد من حذف "'+p.title+'"?'))return;const {error}=await supabaseClient.from("projects").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("user_id",currentUser.id);if(error)return showToast(error.message,"error");showToast("تم حذف المشروع بنجاح","success");await loadProjects()}
function setupRealtime(){supabaseClient.channel("dashboard-"+currentUser.id).on("postgres_changes",{event:"*",schema:"public",table:"projects",filter:"user_id=eq."+currentUser.id},async()=>{await loadProjects()}).on("postgres_changes",{event:"*",schema:"public",table:"profiles",filter:"id=eq."+currentUser.id},async()=>{await loadProfile()}).subscribe()}
init();