let currentUser=null,projects=[],profile=null;
async function init(){currentUser=await requireAuth();if(!currentUser)return;await Promise.all([loadProfile(),loadProjects()]);setupRealtime()}
async function loadProfile(){const {data,error}=await supabaseClient.from("profiles").select("credits,name,full_name,avatar_url").eq("id",currentUser.id).maybeSingle();if(error){showToast("تعذر تحميل الرصيد: "+error.message,"error");return}profile=data||{};renderCredits();const a=document.getElementById("avatar");if(a)a.innerHTML=profile.avatar_url?'<img src="'+esc(profile.avatar_url)+'" alt="">':"👤"}
function renderCredits(){const c=Math.max(0,Number(profile?.credits??0));document.getElementById("credits-value").textContent=c+" / 50";document.getElementById("credits-pill").textContent="⚡ "+c+" / 50"}
async function loadProjects(){const loading=document.getElementById("loading");loading.style.display="block";const {data,error}=await supabaseClient.from("projects").select("id,title,prompt,language,style,status,created_at,updated_at,scenes(id,scene_index,image_url),render_jobs(id,status,output_url,error_message,created_at)").eq("user_id",currentUser.id).is("deleted_at",null).order("created_at",{ascending:false});loading.style.display="none";if(error)return showToast("فشل تحميل المشاريع: "+error.message,"error");projects=data||[];updateStats();renderProjects()}
function updateStats(){document.getElementById("stat-total").textContent=projects.length;document.getElementById("stat-completed").textContent=projects.reduce((n,p)=>n+(p.render_jobs||[]).filter(j=>j.status==="completed").length,0);document.getElementById("stat-processing").textContent=projects.filter(p=>(p.render_jobs||[]).some(j=>["queued","processing"].includes(j.status))).length}
function esc(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}
function statusFor(p){const jobs=p.render_jobs||[];if(jobs.some(j=>j.status==="completed"))return["جاهز","badge-success"];if(jobs.some(j=>j.status==="processing"))return["قيد المعالجة","badge-processing"];if(jobs.some(j=>j.status==="queued"))return["في الانتظار","badge-queued"];if(jobs.some(j=>j.status==="failed"))return["فشل","badge-failed"];return["مسودة","badge-draft"]}
function projectCard(p){const image=(p.scenes||[]).slice().sort((a,b)=>(a.scene_index||0)-(b.scene_index||0)).find(s=>s.image_url)?.image_url||"";const jobs=p.render_jobs||[];const images=(p.scenes||[]).filter(s=>s.image_url).length;const videos=jobs.filter(j=>j.status==="completed").length;const [status,badge]=statusFor(p);const bg=image?"style=\"background-image:url('"+esc(image)+"')\"":"";return '<article class="project-card"><a class="project-thumb" '+bg+' href="/project.html?id='+encodeURIComponent(p.id)+'"><span class="badge '+badge+'">'+status+'</span><span class="thumb-icon">'+(image?"":"🎬")+'</span></a><div class="project-info"><div class="project-heading"><h3>'+esc(p.title)+'</h3><button class="card-menu" onclick="toggleMenu(event,\''+p.id+'\')" aria-label="خيارات المشروع">⋮</button></div><div class="project-meta"><span>'+images+' صور · '+videos+' فيديو</span><span>'+new Date(p.created_at).toLocaleDateString("ar-MA")+'</span></div></div><div class="project-menu" id="menu-'+p.id+'"><button onclick="renameProject(\''+p.id+'\')">✎ إعادة التسمية</button><button onclick="duplicateProject(\''+p.id+'\')">⧉ نسخ</button><button onclick="shareProject(\''+p.id+'\')">↗ مشاركة</button><button '+(videos?'':'disabled')+' onclick="downloadProject(\''+p.id+'\')">↓ تنزيل</button><button class="danger-text" onclick="deleteProject(\''+p.id+'\')">⌫ حذف</button></div></article>'}
function renderProjects(){const g=document.getElementById("projects-grid"),e=document.getElementById("empty-state");if(!projects.length){g.innerHTML="";e.style.display="block";return}e.style.display="none";g.innerHTML=projects.map(projectCard).join("")}
function toggleMenu(e,id){e.preventDefault();e.stopPropagation();document.querySelectorAll(".project-menu.open").forEach(x=>x.classList.remove("open"));document.getElementById("menu-"+id)?.classList.toggle("open")}
document.addEventListener("click",()=>document.querySelectorAll(".project-menu.open").forEach(x=>x.classList.remove("open")));
async function renameProject(id){const p=projects.find(x=>x.id===id);if(!p)return;const next=prompt("اسم المشروع:",p.title);if(!next||next.trim()===p.title)return;const {error}=await supabaseClient.from("projects").update({title:next.trim(),updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",currentUser.id);if(error)return showToast(error.message,"error");showToast("تم تغيير الاسم","success");loadProjects()}
async function duplicateProject(id){const o=projects.find(p=>p.id===id);if(!o||!confirm("إنشاء نسخة من المشروع؟"))return;const {data:n,error}=await supabaseClient.from("projects").insert({user_id:currentUser.id,title:o.title+" (نسخة)",prompt:o.prompt||o.title,language:o.language||"Arabic",style:o.style||"informative",status:"draft"}).select().single();if(error)return showToast(error.message,"error");const {data:ss,error:se}=await supabaseClient.from("scenes").select("scene_index,title,visual_prompt,image_url,sfx_prompt,sfx_url,duration_seconds,status").eq("project_id",id).order("scene_index");if(se)return showToast(se.message,"error");if(ss?.length){const {error:ie}=await supabaseClient.from("scenes").insert(ss.map(s=>({...s,project_id:n.id,status:s.status==="failed"?"draft":s.status})));if(ie)return showToast(ie.message,"error")}showToast("تم نسخ المشروع","success");loadProjects()}
async function deleteProject(id){const p=projects.find(x=>x.id===id);if(!p||!confirm("حذف «"+p.title+"»؟"))return;const {error}=await supabaseClient.from("projects").update({deleted_at:new Date().toISOString()}).eq("id",id).eq("user_id",currentUser.id);if(error)return showToast(error.message,"error");showToast("تم حذف المشروع","success");loadProjects()}
async function shareProject(id){const url=location.origin+"/project.html?id="+encodeURIComponent(id);try{if(navigator.share)await navigator.share({title:"InkSpire",url});else{await navigator.clipboard.writeText(url);showToast("تم نسخ رابط المشروع","success")}}catch(e){}}
function downloadProject(id){const p=projects.find(x=>x.id===id),j=(p?.render_jobs||[]).find(x=>x.status==="completed"&&x.output_url);if(!j)return showToast("الفيديو غير جاهز بعد","error");const a=document.createElement("a");a.href=j.output_url;a.download=(p.title||"inkspire-video")+".mp4";a.target="_blank";a.click()}
function setupRealtime(){supabaseClient.channel("dashboard-"+currentUser.id).on("postgres_changes",{event:"*",schema:"public",table:"projects",filter:"user_id=eq."+currentUser.id},loadProjects).on("postgres_changes",{event:"*",schema:"public",table:"profiles",filter:"id=eq."+currentUser.id},loadProfile).subscribe()}
init();