let user,projectId,project,scenes=[],activeJob=null,polling=null;
async function init(){user=await requireAuth();if(!user)return;projectId=new URLSearchParams(location.search).get("id");if(!projectId)return showError("معرّف المشروع غير موجود.");deleteBtn.onclick=deleteCurrentProject;genBtn.onclick=generateScenes;renderBtn.onclick=startRender;rerender.onclick=startRender;await loadProject();await loadCredits()}
async function loadCredits(){const {data}=await supabaseClient.from("profiles").select("credits").eq("id",user.id).maybeSingle();if(data)creditsPill.textContent="⚡ "+Math.max(0,Number(data.credits))+" / 50"}
async function loadProject(){const {data,error}=await supabaseClient.from("projects").select("id,title,status,prompt,style,created_at,updated_at,scenes(id,scene_index,title,visual_prompt,image_url,sfx_url,duration_seconds,status),render_jobs(id,status,progress,output_url,error_message,created_at)").eq("id",projectId).eq("user_id",user.id).is("deleted_at",null).single();if(error||!data)return showError("تعذر العثور على المشروع أو لا تملك صلاحية الوصول إليه.");project=data;scenes=(data.scenes||[]).sort((a,b)=>a.scene_index-b.scene_index);activeJob=(data.render_jobs||[]).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at))[0]||null;title.textContent=data.title;loading.style.display="none";content.style.display="block";renderScenes();renderVideo();renderActions();if(activeJob?.status==="queued"||activeJob?.status==="processing")startPolling()}
function esc(s){const d=document.createElement("div");d.textContent=s??"";return d.innerHTML}
function renderScenes(){sceneCount.textContent=scenes.length;if(!scenes.length){scenesEl.innerHTML='<div class="empty-state"><div class="empty-icon">✦</div><p>مازال ما تولد حتى مشهد.</p></div>';genBtn.style.display="inline-flex";return}genBtn.style.display="inline-flex";genBtn.textContent="↻ إعادة توليد المشاهد";scenesEl.innerHTML=scenes.map((s,i)=>'<div class="scene-card"><div style="padding:10px;font-weight:700;display:flex;justify-content:space-between"><span>مشهد '+(i+1)+'</span><span class="muted">'+s.duration_seconds+'ث</span></div>'+(s.image_url?'<img loading="lazy" decoding="async" src="'+esc(s.image_url)+'" class="scene-image" alt="">':'<div class="scene-placeholder">🎨</div>')+'<div class="scene-text">'+esc(s.visual_prompt||s.title||"")+'</div>'+(!s.image_url?'<button class="btn-secondary" onclick="generateImage(\''+s.id+'\')">🎨 إنشاء الصورة · 1 Credit</button>':'<button class="btn-secondary" disabled>✓ الصورة جاهزة</button>')+'</div>').join("")}
function renderActions(){const all=scenes.length>0&&scenes.every(s=>s.image_url);renderSection.style.display=all&&!["queued","processing"].includes(activeJob?.status)?"block":"none"}
function renderVideo(){if(activeJob?.status==="completed"&&activeJob.output_url){videoSection.style.display="block";video.src=activeJob.output_url;download.href=activeJob.output_url;renderSection.style.display="none"}}
async function generateScenes(){genBtn.disabled=true;showProgress("جارٍ توليد المشاهد...",10);let cfg={};try{cfg=JSON.parse(localStorage.getItem("project-"+projectId+"-config")||"{}")}catch{}const lang=localStorage.getItem("inkspire-language")||"en";const languageNames={ar:"Arabic",en:"English",fr:"French",es:"Spanish",de:"German",it:"Italian",pt:"Portuguese",tr:"Turkish",ja:"Japanese",ko:"Korean",zh:"Chinese",ru:"Russian",hi:"Hindi"};const {data,error}=await supabaseClient.functions.invoke("generate-scenes",{body:{project_id:projectId,topic:cfg.topic||project.prompt||project.title,duration:cfg.duration||60,style:cfg.style||project.style||"informative",language:languageNames[lang]||"English",locale:lang}});if(error){let detail=error.message||"تعذر توليد المشاهد.";try{const ctx=error.context;if(ctx){const body=await ctx.json();detail=body?.error||detail;if(body?.provider_message)detail+=": "+body.provider_message}}catch{}showError(detail)}else{await loadProject();showToast("تم توليد المشاهد بنجاح — جاري إنشاء الصور...","success");for(let i=0;i<scenes.length;i++){if(!scenes[i].image_url){showProgress("جاري إنشاء صورة المشهد "+(i+1)+" من "+scenes.length+"...",20+Math.round(i*70/scenes.length));const r=await generateImage(scenes[i].id,true);if(!r)break}}await loadProject();renderActions()}genBtn.disabled=false;hideProgress()}
async function generateImage(id,silent=false){const s=scenes.find(x=>x.id===id);if(!s)return;if(!silent)showToast("جارٍ إنشاء الصورة...","info",12000);const {data,error}=await supabaseClient.functions.invoke("generate-image",{body:{project_id:projectId,scene_id:id,prompt:s.visual_prompt||s.title||"cinematic scene",size:"1536x1024"}});if(error){if(!silent)showError(error.message||"تعذر إنشاء الصورة.");return false}if(data?.credits_remaining!==undefined){creditsPill.textContent="⚡ "+data.credits_remaining+" / 50";showToast("تم خصم 1 Credit · المتبقي: "+data.credits_remaining,"info")}if(data?.image_url){s.image_url=data.image_url;s.status="ready";renderScenes();renderActions();if(!silent)showToast("تم إنشاء الصورة بنجاح","success");return true}if(!data?.image_base64){if(!silent)showError("تعذر الحصول على الصورة.");return false}const mime=data.content_type||"image/png";const bytes=Uint8Array.from(atob(data.image_base64),ch=>ch.charCodeAt(0));const ext=mime.includes("jpeg")?"jpg":"png";const path=user.id+"/"+projectId+"/scene-"+id+"-"+Date.now()+"."+ext;const {error:upErr}=await supabaseClient.storage.from("inkspire-images").upload(path,bytes,{contentType:mime,upsert:true,cacheControl:"3600"});if(upErr){if(!silent)showError(upErr.message);return false}const {data:signed,error:signedErr}=await supabaseClient.storage.from("inkspire-images").createSignedUrl(path,60*60*24*7);if(signedErr){if(!silent)showError(signedErr.message);return false}const {error:uerr}=await supabaseClient.from("scenes").update({image_url:signed.signedUrl,status:"ready"}).eq("id",id).eq("project_id",projectId);if(uerr){if(!silent)showError(uerr.message);return false}s.image_url=signed.signedUrl;s.status="ready";renderScenes();renderActions();if(!silent)showToast("تم إنشاء الصورة بنجاح","success");return true}
async function startRender(){if(!scenes.length||!scenes.every(s=>s.image_url))return showError("يجب أن تحتوي جميع المشاهد على صور قبل بدء التصيير.");renderSection.style.display="none";showProgress("جارٍ بدء التصيير...",20);const {data,error}=await supabaseClient.functions.invoke("create-render-job",{body:{project_id:projectId}});if(error)return showError(error.message);activeJob=data.job||{id:data.job_id,status:"queued"};startPolling()}
function startPolling(){if(polling)return;progress.style.display="block";polling=setInterval(async()=>{if(document.visibilityState!=="visible")return;const {data}=await supabaseClient.from("render_jobs").select("id,status,progress,output_url,error_message").eq("id",activeJob.id).eq("project_id",projectId).single();if(!data)return;activeJob={...activeJob,...data};showProgress(data.status==="processing"?"جارٍ تصيير الفيديو...":data.status==="queued"?"في الانتظار...":"",data.progress||0);if(data.status==="completed"){clearInterval(polling);polling=null;hideProgress();renderVideo();showToast("الفيديو جاهز!","success")}else if(data.status==="failed"){clearInterval(polling);polling=null;hideProgress();showError("فشل تصيير الفيديو: "+(data.error_message||"خطأ غير معروف"))}},3000)}
function showProgress(t,p){progress.style.display="block";progressTitle.textContent=t;progressFill.style.width=p+"%";progressStatus.textContent=p+"%"}
function hideProgress(){progress.style.display="none"}
function showError(m){error.textContent=m;error.style.display="block";window.scrollTo({top:0,behavior:"smooth"})}
async function deleteCurrentProject(){if(!confirm("هل أنت متأكد من حذف هذا المشروع؟"))return;const {error:e}=await supabaseClient.from("projects").update({deleted_at:new Date().toISOString()}).eq("id",projectId).eq("user_id",user.id);if(e)return showError(e.message);location.href="/dashboard.html"}
init();
const loading=document.getElementById("loading"),content=document.getElementById("content"),title=document.getElementById("title"),deleteBtn=document.getElementById("delete"),genBtn=document.getElementById("generate-scenes"),scenesEl=document.getElementById("scenes"),sceneCount=document.getElementById("scene-count"),renderSection=document.getElementById("render-section"),renderBtn=document.getElementById("render"),videoSection=document.getElementById("video-section"),video=document.getElementById("video"),download=document.getElementById("download"),rerender=document.getElementById("rerender"),progress=document.getElementById("progress"),progressTitle=document.getElementById("progress-title"),progressFill=document.getElementById("progress-fill"),progressStatus=document.getElementById("progress-status"),error=document.getElementById("error"),creditsPill=document.getElementById("credits-pill");